import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css"
import { initializeDatabase } from "../db";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await initializeDatabase();
  return (
    <html lang="en">
      <body className="bg-gray-100">{children}</body>
    </html>
  );
}
